### ISSUE TITLE
Provide safety by using URL-encoding

### ISSUE THREAD

**Issue by astro** [bitemyapp/bloodhound#38]
Hi

Thank you for publishing this nice library.

Wrapped in its own type, I expected `DocId` to safely handle any input. However, `indexDocument` throws an `InvalidUrlException` at me because I've got slashes and spaces in there. Would you please add automatic URL encoding?

If doing this by default really hampers with performance, could we at least expose encoding functionality as courtesy to users?

**Comment by bitemyapp** [comment]
@astro usually what I do is provide the nice function under a normal name, then a more "raw" one with a prime tick after the name. Like: `func` vs. `func'`

Could you provide an example of such an ID so I can add it to the test suite?

**Comment by astro** [comment]
```haskell
{-# LANGUAGE OverloadedStrings #-}

DocID "http://example.com/feed.xml http://example.com/post/1"
```

**Comment by bitemyapp** [comment]
@astro alrighty then. I'll see if I can figure out a design that improves safety without being too obnoxious.

**Comment by MaxDaten** [comment]
Hi, thanks for this library from me, too.

> Wrapped in its own type, I expected DocId to safely handle any input. However, indexDocument throws an InvalidUrlException at me because I've got slashes and spaces in there.

Even further on the Elasticsearch side an exception is throw if i try to escape the `DocId` on my own. 

## Short example

```

import Database.Bloodhound as E
import Network.URI as URI
import Network.HTTP.Client
import Data.Text as T


server = E.Server "http://192.168.99.100:9200"
libraryIndex = E.IndexName "library"
pageMapping  = E.MappingName "page"
docMapping   = E.MappingName "document"

runBH' = withBH defaultManagerSettings server

main = do
  let doc = E.DocId $ T.pack $ URI.escapeURIString URI.isAllowedInURI "Hello World"
  print doc
  print =<< runBH' (E.getDocument libraryIndex docMapping doc)
```

## Execution

```
DocId "Hello%20World"
*** Exception: NoResponseDataReceived
```

## Exception on Elasticsearch

```
[2015-10-07 08:12:58,245][WARN ][http.netty               ] [Uatu] Caught exception while handling client http traffic, closing connection [id: 0xbfe0f66d, /192.168.99.1:53186 => /172.17.0.4:9200]
java.lang.IllegalArgumentException: invalid version format: WORLD HTTP/1.1
	at org.elasticsearch.common.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:94)
	at org.elasticsearch.common.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:62)
	at org.elasticsearch.common.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:75)
	at org.elasticsearch.common.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:191)
	at org.elasticsearch.common.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102)
	at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
	at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2015-10-07 08:12:58,250][WARN ][http.netty               ] [Uatu] Caught exception while handling client http traffic, closing connection [id: 0xbfe0f66d, /192.168.99.1:53186 :> /172.17.0.4:9200]
java.lang.IllegalArgumentException: empty text
```

# Proposal

Maybe it is possible to avoid `URI.ByteString` and just rely on `Network.URI` with its escape functions like `escapeURIString` from above. Maybe it is even possible to avoid [Database.Bloodhound.Client.setURI](https://github.com/bitemyapp/bloodhound/blob/master/src/Database/Bloodhound/Client.hs#L639-L659)?
